---

   - name: Install SUSE security checker
     zypper:
       name: ['seccheck', 'yast2-mail']
       state: present

   - name: Enable Monthy Seccheck Reports Service
     systemd:
       name: seccheck-monthly.timer
       state: started
       enabled: yes

   - name: Enable Automatic Logout Reports Service
     systemd:
       name: seccheck-autologout.timer
       state: started
       enabled: yes
