---

- name: Enable tuned service
  service:
    name: tuned
    state: started
    enabled: yes

- name: Enable Saptune Solution HANA
  command: |
      tuned-adm profile sap-hana

- name: Activate tuned-adm
  command: "tuned-adm active"

- name: Configure Sysctl Parameters
  sysctl:
    name="{{ item.pname }}"
    value="{{ item.value }}"
    sysctl_set=yes
    state=present
    reload=yes
  with_items:
  - { pname: 'net.core.somaxconn', value: '4096'}
  - { pname: 'net.ipv4.tcp_max_syn_backlog', value: '8192'}
  - { pname: 'net.ipv4.tcp_tw_reuse', value: '1'}
  - { pname: 'net.ipv4.tcp_timestamps', value: '1'}
  - { pname: 'net.ipv4.tcp_window_scaling', value: '1'}
  - { pname: 'net.ipv4.tcp_slow_start_after_idle', value: '0'}
  - { pname: 'net.ipv4.ip_local_port_range', value: '40000 65300'}
  - { pname: 'net.ipv4.tcp_wmem', value: '4096 16384 4194304'}
  - { pname: 'net.ipv4.tcp_rmem', value: '4096 16384 4194304'}
  - { pname: 'net.core.rmem_max', value: '4194304'}
  - { pname: 'net.core.wmem_max', value: '4194304'}
  - { pname: 'net.ipv4.tcp_slow_start_after_idle', value: '0'}
  - { pname: 'kernel.pid_max', value: '4194304'}
  - { pname: 'kernel.pid_max', value: '4194304'}

- name: Gathering service facts
  service_facts:
  register: services_state

- name: Disable ABRT Service
  service:
    name: abrtd
    state: stopped
    enabled: no
  when: services_state.ansible_facts.services["abrtd.service"]|default

- name: Disable ABRT-CCPP Service
  service:
    name: abrtd-ccpp
    state: stopped
    enabled: no
  when: services_state.ansible_facts.services["abrtd-ccpp.service"]|default


- name: To disable core core file creation for all users
  copy:
    content: |
             * soft core 0
             * hard core 0
    dest: /etc/security/limits.d/99-sap.conf

- name: Configure CPU Governor for performance
  lineinfile:
    path: /etc/rc.d/rc.local
    line: cpupower frequency-set -g performance

- name: Configuring System Parameters
  template:
    src=files/boot-local
    dest=/etc/init.d/boot.local
    owner=root
    group=root
    mode=0644
    backup=yes

- name: Change grub File Parameters in to /etc/default/grub
  lineinfile:
    path=/etc/default/grub
    regexp="^GRUB_CMDLINE_LINUX="
    line='GRUB_CMDLINE_LINUX="resume={{ ansible_proc_cmdline.resume }} rd.lvm.lv={{ ansible_proc_cmdline['rd.lvm.lv'].0 }} rd.lvm.lv={{ ansible_proc_cmdline['rd.lvm.lv'].1 }} rhgb quiet crashkernel=auto transparent_hugepage=never numa_balancing=disable intel_idle.max_cstate=1 processor.max_cstate=1"'
  register: grub

- name: Run the grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg command to generate the grub configuration file
  command: "grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg"
  when: grub.changed

- name: Rebooting ...
  shell: sleep 2 && /sbin/shutdown -r now "Reboot required for grub"
  async: 1
  poll: 0
  ignore_errors: true
  when: grub.changed
  register: rebooting

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 900
    sleep: 15
    delay: 30
  when: rebooting.changed

- name: Tune core_collector parameters for kdump.conf
  replace:
    path: /etc/kdump.conf
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  with_items:
    - {regex: '^core_collector(.+)$', replace: 'core_collector makedumpfile -d 31 -c --message-level 7'}
    - {regex: '#\sfailure_action(.+)$', replace: 'failure_action poweroff'}


- name: Set as specified in /etc/sysctl.conf so system will panic on NMI
  sysctl:
    name="{{ item.pname }}"
    value="{{ item.value }}"
    sysctl_set=yes
    state=present
    reload=yes
  with_items:
  - { pname: 'kernel.unknown_nmi_panic', value: '1' }
  - { pname: 'kernel.panic_on_unrecovered_nmi', value: '1' }
  - { pname: 'kernel.panic_on_io_nmi', value: '1' }

- name: Enable kdump Service
  service:
    name: kdump
    state: started
    enabled: yes

- name: Build Initramfs
  command: "dracut -f -v"
  register: initramfs

- name: Rebooting ...
  shell: sleep 2 && /sbin/shutdown -r now "Reboot required for grub"
  async: 1
  poll: 0
  ignore_errors: true
  when: initramfs.changed
  register: rebooting

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 900
    sleep: 15
    delay: 30
  when: rebooting.changed

