---

  - name: Set the state of a virtual machine to poweron using MoID
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ guest_name }}"
      state: powered-on
    delegate_to: localhost
    register: deploy

