---

  # Persistent Memory Configuration
  # If Persistent Memory  defined
  # You can enable this feature (true/false)
  pmem: false

  #### ESXI Guest Based Variables ####
  # Destination Hypervisor
  esxi_hostname: 10.254.254.4
  # ESXI Guest Name
  guest_name: lxhana02
  # Guest Memory
  memory_mb: 32768
  # Number of Total CPU
  num_cpus: 16
  # CPU Cores Per Socket
  num_cpu_cores_per_socket: 8
  # Public Network Interface
  network: "VM Network"
  # Replication Network Interface
  rep_network: "HANA Rep"
  # ESXI Guest Folder "Datacenter/vm"
  guest_folder: HPETR/vm
  # ESXI Datacenter
  datacenter: HPETR
  # Operating System Disc Size
  os_disc_size_gb: 156
  # Operating System Disk Datastore
  os_disc_datastore: SVT_DS02

  # SAP Hana Storage Parameters
  # /hana/data Storage size
  hana_data_size_gb: 514
  # /hana/data Storage Datastore
  hana_data_datastore: SVT_DS02
  # /hana/log Storage size
  hana_log_size_gb: 514
  # /hana/log Storage Datastore
  hana_log_datastore: SVT_DS02
  # /hana/shared Storage size
  hana_shared_size_gb: 514
  # /hana/share Datastore
  hana_shared_datastore: SVT_DS02
  # /usr/sap Storage size
  hana_usr_sap_size_gb: 102
  # /usr/sap Storage Datastore
  hana_usr_sap_datastore: SVT_DS02

  #### Host Based Variables ####
  # Redhat Satellite Server Information
  sat_fqdn: 
  sat_user: 
  sat_passwd: 
  sat_org: 
  sat_loc: 
  sat_host_grp: 
  sat_act_key: 

  # access.redhat.com Information
  rhn_org_id: 12789368
  rhn_act_key: SAP
  rhel_rlease: 8.6
  

  # OS Data Logical Drive
  OS_Partition: /dev/sda2

  # Operating System Logical disk Parameters
  hana_data_disks:
      partition: /dev/sdb
      volume_group: vg_hana_data
  hana_shared_disks:
      partition: /dev/sde
      volume_group: vg_hana_shared
  hana_log_disks:
      partition: /dev/sdd
      volume_group: vg_hana_log
  hana_usr_sap_disks:
      partition: /dev/sdc
      volume_group: vg_hana_usr_sap 

  hanavols:
    hana_shared:
      size: 512G
      vol: vg_hana_shared
      lv: lv_hana_shared
      mountpoint: /hana/shared
      fs_type: xfs
    hana_data:
      size: 512G
      vol: vg_hana_data
      lv: lv_hana_data
      mountpoint: /hana/data
      fs_type: xfs
    hana_logs:
      size: 512G
      vol: vg_hana_log
      lv: lv_hana_log
      mountpoint: /hana/log
      fs_type: xfs
    usr_sap:
      size: 100G
      vol: vg_hana_usr_sap
      lv: lv_hana_usr_sap
      mountpoint: /usr/sap
      fs_type: xfs

  ### Hana DB Configuration Parameters ###
  # Components ( Valid values: all | client | es | ets | lcapps | server | smartda | streaming | rdsync | xs | studio | afl | pos | sal | sca | sop | trd | udf )
  #components: server,client
  components: server,client
  # Action ( Default: exit; Valid values: install | update | extract_components )
  action: install
  # SAP HANA System ID (ex: HDB)
  sid: PED
  # Instance Number (ex: 00)
  number: "0"
  # Database Mode ( Default: single_container; Valid values: single_container | multiple_containers )
  db_mode: multiple_containers
  # System Usage ( Default: custom; Valid values: production | test | development | custom )
  system_usage: production
  # SAP Host Agent User (sapadm) Password
  sapadm_password: HP1nv3nt
  # System Administrator Password
  system_admin_password: HP1nv3nt
  # Database User (SYSTEM) Password
  system_user_password: HP1nv3nt
  # Restrict maximum memory allocation? ( Default: off; Valid values: off | on )
  restrict_max_mem: off
  # Maximum Memory Allocation in MB
  max_mem: 0

  # Hana DB Replication Configuration Parameters
  primary_server:
    hostname: lxhana03
    public_ip: 10.254.254.143
    replication_ip: 10.15.100.143

  secondary_server:
    hostname: lxhana04
    public_ip: 10.254.254.144
    replication_ip: 10.15.100.144

  # Replication Type ( sync | syncmem | async )
  replication_type: syncmem

  # Replication Operation Mode ( logreplay )
  operation_mode: logreplay

  # Hana Key Exchange Temporary Storage ( logreplay )
  sap_hana_hsr_keyexchange_tmp: /home/hpe/ansible/ansible-sap-hana-deploy-rhel/hsr_keyexchange_tmp

